// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs(title, content, user_id, created, updated) VALUES ($1, $2, $3, $4, $5) RETURNING id, title, content, user_id, created, updated
`

type CreateBlogParams struct {
	Title   string       `json:"title"`
	Content string       `json:"content"`
	UserID  int32        `json:"user_id"`
	Created sql.NullTime `json:"created"`
	Updated sql.NullTime `json:"updated"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, createBlog,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.Created,
		arg.Updated,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createUsers = `-- name: CreateUsers :one
INSERT INTO users(username,email,password, created, updated) VALUES ($1, $2, $3, $4, $5) RETURNING id, username, created, updated
`

type CreateUsersParams struct {
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Password string       `json:"password"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

type CreateUsersRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (CreateUsersRow, error) {
	row := q.db.QueryRowContext(ctx, createUsers,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Created,
		arg.Updated,
	)
	var i CreateUsersRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username,email, created, updated FROM users WHERE id = $1
`

type GetUserRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, content, user_id, created, updated FROM blogs ORDER BY id
`

func (q *Queries) ListBlogs(ctx context.Context) ([]Blog, error) {
	rows, err := q.db.QueryContext(ctx, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username,email, created, updated FROM users ORDER BY id
`

type ListUsersRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
